export const JT = {};

JT.sheetTheme = {
  default: "MM3.THEME.default",
  green: "MM3.THEME.green",
  freedomcity: "MM3.THEME.freedomcity",
  techblue: "MM3.THEME.techblue",
  techblue2: "MM3.THEME.techblue2",
  bloodred: "MM3.THEME.bloodred",
  bloodred2: "MM3.THEME.bloodred2",
  gothblack: "MM3.THEME.gothblack",
  cosmicblue: "MM3.THEME.cosmicblue",
  starburst: "MM3.THEME.starburst",
  matrixblack: "MM3.THEME.matrixblack",
};

JT.JurnalHeaderFont = {
  "Alegreya Sans SC": "Alegreya Sans SC",
  "Overlock SC": "Overlock SC",
  "Ysabeau SC": "Ysabeau SC",
  Nosifer: "Nosifer",
  Eater: "Eater",
  "Henny Penny": "Henny Penny",
  "Emilys Candy": "Emilys Candy",
  "Jolly Lodger": "Jolly Lodger",
  "Mystery Quest": "Mystery Quest",
  Butcherman: "Butcherman",
  "Metal Mania": "Metal Mania",
  "Trade Winds": "Trade Winds",
  "Freckle Face": "Freckle Face",
  "New Rocker": "New Rocker",
  "Bruno Ace SC": "Bruno Ace SC",
  Bahiana: "Bahiana",
  "Holtwood One SC": "Holtwood One SC",
  "Permanent Marker": "Permanent Marker",
  "Tilt Prism": "Tilt Prism",
  Monoton: "Monoton",
  Underdog: "Underdog",
  Sancreek: "Sancreek",
  "Hammersmith One": "Hammersmith One",
  "Titan One": "Titan One",
  "Walter Turncoat": "Walter Turncoat",
  "Racing Sans One": "Racing Sans One",
  "Contrail One": "Contrail One",
  "Ga Maamli": "Ga Maamli",
  UnifrakturCook: "UnifrakturCook",
  "Manufacturing Consent": "Manufacturing Consent",
  "Encode Sans SC": "Encode Sans SC",
  Aboreto: "Aboreto",
  "Arsenal SC": "Arsenal SC",
  "Alumni Sans SC": "Alumni Sans SC",
  "Bungee Inline": "Bungee Inline",
  "Protest Guerrilla": "Protest Guerrilla",
  "Bowlby One SC": "Bowlby One SC",
};
