export const JT = {};

JT.sheetTheme = {
  default: "JT.THEME.default",
  emeraldcity: "JT.THEME.emeraldcity",
  freedomcity: "JT.THEME.freedomcity",
  techblue: "JT.THEME.techblue",
  techblue2: "JT.THEME.techblue2",
  bloodred: "JT.THEME.bloodred",
  bloodred2: "JT.THEME.bloodred2",
  gothblack: "JT.THEME.gothblack",
  cosmicblue: "JT.THEME.cosmicblue",
  starburst: "JT.THEME.starburst",
  matrixblack: "JT.THEME.matrixblack",
};

JT.JurnalHeaderFont = {
  "Alegreya Sans SC": "Alegreya Sans SC",
  "Overlock SC": "Overlock SC",
  "Ysabeau SC": "Ysabeau SC",
  "Nosifer": "Nosifer",
 "Eater": "Eater",
  "Henny Penny": "Henny Penny",
  "Emilys Candy": "Emilys Candy",
  "Jolly Lodger": "Jolly Lodger",
  "Mystery Quest": "Mystery Quest",
  "Butcherman": "Butcherman",
  "Metal Mania": "Metal Mania",
  "Trade Winds": "Trade Winds",
  "Freckle Face": "Freckle Face",
  "New Rocker": "New Rocker",
  "Bruno Ace SC": "Bruno Ace SC",
  "Bahiana": "Bahiana",
  "Holtwood One SC": "Holtwood One SC",
  "Permanent Marker": "Permanent Marker",
  "Tilt Prism": "Tilt Prism",
  "Monoton": "Monoton",
  "Underdog": "Underdog",
  "Sancreek": "Sancreek",
  "Hammersmith One": "Hammersmith One",
  "Titan One": "Titan One",
  "Walter Turncoat": "Walter Turncoat",
  "Racing Sans One": "Racing Sans One",
  "Contrail One": "Contrail One",
  "Ga Maamli": "Ga Maamli",
  "UnifrakturCook": "UnifrakturCook",
  "Manufacturing Consent": "Manufacturing Consent",
  "Encode Sans SC": "Encode Sans SC",
  "Aboreto": "Aboreto",
  "Arsenal SC": "Arsenal SC",
  "Alumni Sans SC": "Alumni Sans SC",
  "Bungee Inline": "Bungee Inline",
  "Protest Guerrilla": "Protest Guerrilla",
  "Bowlby One SC": "Bowlby One SC",
};
