export const JT = {};

JT.sheetTheme = {
  default: "JT.THEME.default",
  emeraldcity: "JT.THEME.emeraldcity",
  freedomcity: "JT.THEME.freedomcity",
  techblue: "JT.THEME.techblue",
  techblue2: "JT.THEME.techblue2",
  bloodred: "JT.THEME.bloodred",
  bloodred2: "JT.THEME.bloodred2",
  gothblack: "JT.THEME.gothblack",
  cosmicblue: "JT.THEME.cosmicblue",
  starburst: "JT.THEME.starburst",
  matrixblack: "JT.THEME.matrixblack",
};

JT.JournalHeaderFont = {
  "Aboreto": "Aboreto",
  "Aladin": "Aladin",
  "Alegreya Sans SC": "Alegreya Sans SC",
  "Alumni Sans SC": "Alumni Sans SC",
  "Amarante": "Amarante",
  "Anton": "Anton",
  "Anton SC": "Anton SC",
  "Arsenal SC": "Arsenal SC",
  "Atomic Age": "Atomic Age",
  "Aubrey": "Aubrey",
  "Bahiana": "Bahiana",
  "Bangers": "Bangers",
  "Baskerville": "Baskerville",
  "Baskerville SC": "Baskerville SC",
  "Bebas Neue": "Bebas Neue",
  "Blinker": "Blinker",
  "Bokor": "Bokor",
  "Bowlby One SC": "Bowlby One SC",
  "Bruno Ace SC": "Bruno Ace SC",
  "Bungee": "Bungee",
  "Bungee Inline": "Bungee Inline",
  "Bungee Outline": "Bungee Outline",
  "Butcherman": "Butcherman",
  "Caesar Dressing": "Caesar Dressing",
  "Cinzel": "Cinzel",
  "Codystar": "Codystar",
  "Contrail One": "Contrail One",
  "Creepster": "Creepster",
  "DotGothic16": "DotGothic16",
  "Doto": "Doto",
  "Eater": "Eater",
  "Emilys Candy": "Emilys Candy",
  "Encode Sans SC": "Encode Sans SC",
  "Exo": "Exo",
  "Faculty Glyphic": "Faculty Glyphic",
  "Faster One": "Faster One",
  "Fascinate": "Fascinate",
  "Fascinate Inline": "Fascinate Inline",
  "Federo": "Federo",
  "Freckle Face": "Freckle Face",
  "Fredoka": "Fredoka",
  "Ga Maamli": "Ga Maamli",
  "Glass Antiqua": "Glass Antiqua",
  "Goldman": "Goldman",
  "Hammersmith One": "Hammersmith One",
  "Hanalei Fill": "Hanalei Fill",
  "Handjet": "Handjet",
  "Henny Penny": "Henny Penny",
  "Holtwood One SC": "Holtwood One SC",
  "Homenaje One SC": "Homenaje One SC"  ,
  "IM Fell Double Pica SC": "IM Fell Double Pica SC",
  "Jolly Lodger": "Jolly Lodger",
  "Josefin Sans": "Josefin Sans",
  "Julius Sans One": "Julius Sans One",
  "Kalam": "Kalam",
  "Kings": "Kings",
  "Libre Franklin": "Libre Franklin",
  "Limelight": "Limelight",
  "Manufacturing Consent": "Manufacturing Consent",
  "Metal Mania": "Metal Mania",
  "Michroma": "Michroma",
  "Monoton": "Monoton",
  "Mystery Quest": "Mystery Quest",
  "New Rocker": "New Rocker",
  "Nosifer": "Nosifer",
  "Noto Sans": "Noto Sans",
  "NTR": "NTR",
  "Open Sans": "Open Sans",
  "Orbitron SC": "Orbitron SC",
  "Overlock SC": "Overlock SC",
  "Pathway Gothic One": "Pathway Gothic One",
  "Patrick Hand SC": "Patrick Hand SC",
  "Permanent Marker": "Permanent Marker",
  "Pirata One": "Pirata One",
  "Pixelfy Sans": "Pixelfy Sans",
  "Plaster": "Plaster",
  "Pompiere": "Pompiere",
  "Poppins": "Poppins",
  "Press Start 2P": "Press Start 2P",
  "Prompt": "Prompt",
  "Protest Guerrilla": "Protest Guerrilla",
  "Quantico": "Quantico",
  "Racing Sans One": "Racing Sans One",
  "Revalia": "Revalia",
  "Righteous": "Righteous",
  "Roboto": "Roboto",
  "Roboto Condensed": "Roboto Condensed",
  "Roboto Mono": "Roboto Mono",
  "Rubik Glitch": "Rubik Glitch",
  "Russo One": "Russo One",
  "Sarpanch": "Sarpanch",
  "Sancreek": "Sancreek",
  "Secular One": "Secular One",
  "Silkscreen": "Silkscreen",
  "Six Caps": "Six Caps",
  "Smokum": "Smokum",
  "Special Elite": "Special Elite",
  "Sriracha": "Sriracha",
  "Staatliches": "Staatliches",
  "Teko": "Teko",
  "Tektur": "Tektur",
  "Tilt Neon": "Tilt Neon",
  "Tilt Prism": "Tilt Prism",
  "Tilt Warp": "Tilt Warp",
  "Titan One": "Titan One",
  "Trade Winds": "Trade Winds",
  "Underdog": "Underdog",
  "UnifrakturCook": "UnifrakturCook",
  "UnifrakturMaguntia": "UnifrakturMaguntia",
  "Urbanist": "Urbanist",
  "Walter Turncoat": "Walter Turncoat",
  "Volikorn SC": "Volikorn SC",
  "VT323 SC": "VT323 SC",
  "Ysabeau SC": "Ysabeau SC",
  "Zen Tokyo Zoo": "Zen Tokyo Zoo",
  'Modesto Condensed':'Modesto Condensed',
  'Amiri':'Amiri',
  'Signika':"Signika",
  'Bruno Ace':"Bruno Ace"
}

