name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Debug: list all files after checkout
      - name: List repo files
        run: |
          echo "Files in repo:"
          find . -type f

      # Update versioned keys in module.json
      - name: Populate Versioned keys in Manifest
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          version: ${{ github.event.release.tag_name }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

      # Debug: show module.json content after substitution
      - name: Show module.json
        run: cat module.json

      # Create module.zip excluding unnecessary folders
      - name: Create Module Archive
        run: |
          zip -r module.zip . -x ".vscode/*" ".github/*" "module.zip"

      # Debug: check module.zip
      - name: Check module.zip
        run: |
          ls -l module.zip
          unzip -l module.zip

      # Upload module.json and module.zip to release
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.draft }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
